apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: debricked-
spec:
  entrypoint: debricked
  arguments:
    parameters:
      - name: git-url # For example: https://github.com/debricked/go-templates.git
      - name: debricked-token # Consider using kubernetes secrets instead. For more details, see: https://github.com/argoproj/argo-workflows/blob/master/examples/secrets.yaml

  templates:
    - name: debricked
      inputs:
        parameters:
          - name: git-url
          - name: debricked-token
      steps:
        - - name: build
            template: build
            arguments:
              parameters:
                - name: git-url
                  value: "{{inputs.parameters.git-url}}"
        - - name: scan
            template: scan
            arguments:
              parameters:
                - name: git-url
                  value: "{{inputs.parameters.git-url}}"
                - name: debricked-token
                  value: "{{inputs.parameters.debricked-token}}"
              artifacts:
                - name: repository
                  from: "{{steps.build.outputs.artifacts.repository}}"

    - name: build
      inputs:
        parameters:
          - name: git-url
        artifacts:
          - name: repository
            path: /repository
            git: # For more details, see: https://github.com/argoproj/argo-workflows/blob/master/examples/input-artifact-git.yaml
              repo: "{{inputs.parameters.git-url}}"
      outputs:
        artifacts:
          - name: repository
            path: /repository
      container:
        name: 'maven'
        image: maven:3-jdk-11
        workingDir: /repository
        command:
          - mvn
          - dependency:tree
          - -DoutputFile=.debricked-maven-dependencies.tgf
          - -DoutputType=tgf

    - name: scan
      inputs:
        parameters:
          - name: debricked-token
          - name: git-url
        artifacts:
          - name: repository
            path: /repository
      container:
        name: 'debricked-scan'
        image: debricked/debricked-scan:latest
        workingDir: /repository
        command:
          - /bin/sh
          - '-c'
        args:
          - /argo.sh
        env:
          - name: DEBRICKED_TOKEN
            value: "{{inputs.parameters.debricked-token}}"
          - name: DEBRICKED_GIT_URL
            value: "{{inputs.parameters.git-url}}"
